### PR TITLE
Pass application context to adapter setup

### LINKED ISSUE #479: receive_adapter startup failed
**Describe the bug**
When ksrv attempt to start the eventing-gitLab receive_adapter pod, it run into the following error message, which prevents the service from starting successfully:

```
Unable to fetch k8s.io/client-go/kubernetes.Interface from context. This context is not the application context (which is typically given to constructors via sharedmain).
```

I've followed the official documentation for installation and configuration, and my Kubernetes cluster is operational. I've tried searching for similar issues but haven't found a solution yet.

 **Expected behavior**
the eventing-gitLab receive_adapter pod should start up successfully.

 **To Reproduce**
* deploy knative eventing and knative serving in kubernetes cluster
* deploy eventing-gitlab
* create a gitlabsource instance like this:

```yaml
apiVersion: sources.knative.dev/v1alpha1
kind: GitLabSource
metadata:
  name: gitlabsource-pr-comment
  namespace: default
spec:
  eventTypes:
    - "note_events"
  accessToken:
    secretKeyRef:
      name: gitlab-integration-config
      key: token
  secretToken:
    secretKeyRef:
      name: gitlab-secret-token
      key: secret_token
  projectUrl: "https://gitlab-ce.alauda.cn/idp/demo/chatops"
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: default
```

 **Knative release version**

v1.13.1

### PR DESCRIPTION
**Pull request by creydr**
The adapter currently fails on startup due to:

```
Unable to fetch k8s.io/client-go/kubernetes.Interface from context. This context is not the application context (which is typically given to constructors via sharedmain).
```

https://cloud-native.slack.com/archives/C04LGHDR9K7/p1712893639063409

This is because, the "new" adapter requires a context with a kubeclient. This PR addresses it and passes a configured application context to adapter.MainWithContext()

Fixes #479

### CODE REVIEW

File: cmd/receive_adapter/main.go [hunk 1]
```diff
@@ -20,8 +20,14 @@ import (
...
 	gitlabadapter "knative.dev/eventing-gitlab/pkg/adapter"
+	"knative.dev/pkg/injection"
+	"knative.dev/pkg/signals"
 )
 
 func main() {
-	adapter.Main("gitlabsource", gitlabadapter.NewEnvConfig, gitlabadapter.NewAdapter)
+	ctx := signals.NewContext()
+	cfg := injection.ParseAndGetRESTConfigOrDie()
+	ctx, _ = injection.Default.SetupInformers(ctx, cfg)
```
Comment (creydr) [inline cmd/receive_adapter/main.go:30]: @pierDipi or is there another way, to simply get one informer injected (the one with the kubeclient)?

Comment (pierDipi) [reply cmd/receive_adapter/main.go:30]: https://github.com/knative/eventing/blob/1ed11b74e50924e57587848152395e2ebaecfd8f/pkg/adapter/v2/main.go#L146C42-L146C59

Comment (creydr) [reply cmd/receive_adapter/main.go]: :+1: Thanks

**Review by pierDipi — APPROVED** [review]
/lgtm
/approve
